//
//
//

import 'package:casino_plus/src/types/playing_card.dart';

/// e.g. var deck = newDeck();
List<PlayingCard> newDeck() {
  return [
    PlayingCard.spade1,
    PlayingCard.spade2,
    PlayingCard.spade3,
    PlayingCard.spade4,
    PlayingCard.spade5,
    PlayingCard.spade6,
    PlayingCard.spade7,
    PlayingCard.spade8,
    PlayingCard.spade9,
    PlayingCard.spade10,
    PlayingCard.spade11,
    PlayingCard.spade12,
    PlayingCard.spade13,
    PlayingCard.heart1,
    PlayingCard.heart2,
    PlayingCard.heart3,
    PlayingCard.heart4,
    PlayingCard.heart5,
    PlayingCard.heart6,
    PlayingCard.heart7,
    PlayingCard.heart8,
    PlayingCard.heart9,
    PlayingCard.heart10,
    PlayingCard.heart11,
    PlayingCard.heart12,
    PlayingCard.heart13,
    PlayingCard.diamond1,
    PlayingCard.diamond2,
    PlayingCard.diamond3,
    PlayingCard.diamond4,
    PlayingCard.diamond5,
    PlayingCard.diamond6,
    PlayingCard.diamond7,
    PlayingCard.diamond8,
    PlayingCard.diamond9,
    PlayingCard.diamond10,
    PlayingCard.diamond11,
    PlayingCard.diamond12,
    PlayingCard.diamond13,
    PlayingCard.club1,
    PlayingCard.club2,
    PlayingCard.club3,
    PlayingCard.club4,
    PlayingCard.club5,
    PlayingCard.club6,
    PlayingCard.club7,
    PlayingCard.club8,
    PlayingCard.club9,
    PlayingCard.club10,
    PlayingCard.club11,
    PlayingCard.club12,
    PlayingCard.club13,
    PlayingCard.blackJocker,
    PlayingCard.whiteJocker,
  ];
}
